In [2]:
#IMPORT ALL THE IMPORTANT FILE WHICH WE WILL USE IN THIS TASK
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [32]:
#THEN, LOAD THE DATASET FROM THE LIBRARY AND SAVE IT INTO VARIABLE
iris = load_iris()
print(dir(iris))

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [33]:
#HERE, I PRINT THE DESCRIPTION OF THE DATASET...
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [34]:
#NOW, I PRINT THE FEATURES OF OUR DATASET... AS WE CAN SEE THERE ARE FOUR FEATURES OF THE DATASET....
#WE WILL ALSO USE THERE FEATURES BY GIVING OUR OWN VALUES FOR THE PREDICTION
print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [35]:
#HERE, I PRINT THE SHAPE OF OUR DATA, (150,4) IT MEANS OUR DATA HAVE 150 ROWS AND 4 COOLUMNS
print(iris['data'].shape)

(150, 4)


In [36]:
#THESE ARE THE TARGET NAMES WHICH WE WILL PREDICT IN FUTURE
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [15]:
#HERE, I SAVE THE DATA AND TARGET INTO THE VAIABLES SO I CAN TRAIN THEM
X = iris.data
y = iris.target

In [37]:
#HERE, I SPLIT THE OUR DATA INTO 80,20 AND SPLIT THEM INOT TEST AND TRAIN
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [38]:
#HERE WE CAN SEE THE LENGTH OF OUR TRAIN AND TEST DATA
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

120
30
120
30


In [39]:
#SO, NOW WE WILL APPLY MODEL ON THE TRAIND DATA & I APPLY LOGISTIC REGRESSION ON THIS CASE
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [41]:
#THIS PIECE OF CODE SHOWS THE MODEL ACCURACY SCORE WHICH IS 100%
model.score(X_test,y_test)

1.0

In [43]:
#WE TEST OUR MODEL ON TEST DATASET.... HERE O MEAN "SETOSA" , 1 MEANS "VERSICOLOR", 2 MEANS "VIRGINICA"
model.predict(X_test)

array([1, 0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 1, 0, 0, 0, 0, 0,
       0, 0, 2, 1, 1, 1, 1, 1])

In [26]:
y_test

array([0, 1, 2, 2, 1, 2, 2, 0, 2, 2, 1, 0, 2, 1, 1, 2, 2, 1, 0, 0, 2, 0,
       2, 2, 1, 2, 1, 2, 1, 1])

In [28]:
#HERE I GIVE MY SOME OWN VALUES AND YOU CAN SEE IN THE RESULT IS HOWS "0" WHICH MEANS IS SETOSA
model.predict([[4.6,3.2,1.5,0.4]])

array([0])

In [29]:
#HERE I GIVE MY SOME OWN VALUES AND YOU CAN SEE IN THE RESULT IS HOWS "1" WHICH MEANS IS VERSICOLOR
model.predict([[5.6,2.8,4.1,1.2]])

array([1])

In [30]:
#HERE I GIVE MY SOME OWN VALUES AND YOU CAN SEE IN THE RESULT IS HOWS "2" WHICH MEANS IS VIRGINICA
model.predict([[7.6,3.8,6.1,2.2]])

array([2])